modLoader="javafml"
loaderVersion="[36,)"
license="Public Domain"

[[mods]]
modId="exodus"
version="1.1.0"
displayName="Exodus"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Green"
description='''
a Mod with Op Stuff.
'''

[[dependencies.exodus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.exodus]]
    modId="pehkui"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.exodus]]
    modId="compactcrafting"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


